# Dependencies
markdown:         redcarpet
highlighter:	  pygments

# Permalinks
permalink:        pretty

# Setup
title:            Katie Walker
tagline:          Furniture
url:              http://katiewalkerfurniture.com
paginate:         1
baseurl:          /
images:	 	  /public/images/
author:
  name:           Katie Walker
  url:            https://twitter.com/katiewalker
  email:          info@kwf.biz

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      headimage: ""

collections:
  retailers:
    output: true
    headimage: http://images.quru.com/image?src=kwf/workshop/Millmead_Workshop_Katie_Walker_Furniture_S_FL_orig.jpg
  work:
    output: true
    headimage: http://images.quru.com/image?src=kwf/workshop/Millmead_Workshop_Katie_Walker_Furniture_S_FL_orig.jpg
  contact:
    output: true
    headimage: http://images.quru.com/image?src=kwf/workshop/Millmead_Workshop_Katie_Walker_Furniture_S_FL_orig.jpg
  news:
    output: true
    headimage: http://images.quru.com/image?src=kwf/workshop/Millmead_Workshop_Katie_Walker_Furniture_S_FL_orig.jpg
  links:
    output: true
    headimage: http://images.quru.com/image?src=kwf/workshop/Millmead_Workshop_Katie_Walker_Furniture_S_FL_orig.jpg
