title:            Katie Walker
tagline:          Furniture design
url:              http://www.katiewalkerfurniture.com
# paginate:        1
baseurl:          /
author:
  name:           Roland Whitehead
  url:            https://twitter.com/rolandw
  email:          i.am@rolandw.me
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

version:          1.0.0
github:
  repo:           https://github.com/katiewalker.furniture/katiewalker.furniture

collections:
  retailers:
    output: true
  work:
    output: true
  contact:
    output: true
  news:
    output: true
  links:
    output: true
  exhibitions:
    output: true
  unused:
    output: false
