# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  math_engine: mathjax
timezone:         Europe/London
maruku:
  use_divs:       true
  fenced_code_blocks: true

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false

# Permalinks
permalink:        pretty

# Setup
title:            Katie Walker
tagline:          Furniture design
url:              http://www.katiewalkerfurniture.com
# paginate:         1
baseurl:          /
author:
  name:           Roland Whitehead
  url:            https://twitter.com/rolandw
  email:          i.am@rolandw.me
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'


# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/katiewalker.furniture/katiewalker.furniture

collections:
  retailers:
    output: true
  work:
    output: true
  contact:
    output: true
  news:
    output: true
  links:
    output: true
  exhibitions:
    output: true
  unused:
    output: false
